 server:
  port: 6273
  
  
 spring:
  application:
    name: UOM-TEST-APP
    
 eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: http://alienschat.cfapps.io/eureka/
  instance:
    hostname: http://alienschat.cfapps.io
