 server:
  port: 6273
  
  
 spring:
  application:
    name: UOM-TEST-APP
    
 eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: http://sa-warehouseserviceregistry-sandbox.mymicroapps.net/eureka/
  instance:
    hostname: http://sa-warehouseserviceregistry-sandbox.mymicroapps.net/